web:
  build: ./
  command: sh -c 'npm install && node server.js'
  ports: 
    - '3000:3000'
  volumes:
    - /home/alexis/Escritorio/BBDDNSQL/TP2/parte-1-StarWars/codigo/api:/api
  links:
    - "db:redis"

db:
  image: redis
  ports:
    - "6379:6379"